name: app
description: Flutter project template.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.24.3'

dependencies:
  auto_route: ^9.2.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  hooks_riverpod: ^2.0.2
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.2.1
  build_runner: ^2.3.2
  riverpod_generator: ^2.6.2
  auto_route_generator: ^9.0.0
  pedantic_mono: any

flutter:
  uses-material-design: true
