name: app
description: Flutter project template.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  auto_route: ^9.2.2
  clock: ^1.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.2.1
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  auto_route_generator: ^9.0.0
  pedantic_mono: any
  fake_async: ^1.3.1
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
